server:
  port: 8761

#Eureka properties
eureka:
  #Eureka setting for other service run outside the docker-container
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


---

eureka:
  instance:
    hostname: eureka